# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [4]:
import numpy as np

In [5]:
# Exercise 1
z = np.arange(1,11)
print(z)

[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [7]:
# Exercise 2
b = np.array([[1,2,3],[3,4,5],[4,9,7]])
print(b)

[[1 2 3]
 [3 4 5]
 [4 9 7]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [9]:
# Exercise 3
x=10
y=5
array_nbr=np.linspace(0,y,x)
array_nbr = np.interp(
    np.linspace(0, x- 1, x),
    np.arange(len(array_nbr)),
    array_nbr
).astype(int)
print(array_nbr)

[0 0 1 1 2 2 3 3 4 5]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [10]:
matrix_of_5=np.eye(5)
print(matrix_of_5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [11]:
# Exercise 5
matrix_of_4=np.eye(4)
print(matrix_of_4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [14]:
# Exercise 6
t=np.array([[1,5,3,4],[4,6,7,9]])
print(t.shape)

(2, 4)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [15]:
# Exercise 7
a=np.arange(16)
Matrix=a.reshape(4,4)
print(Matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [18]:
# Exercise 8
Y=np.array([1,2,3,4,5,6])
print(type(Y))

<class 'numpy.ndarray'>



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [19]:
# Exercise 9
x=np.arange(1,101)
even_number =x[x % 2==0]
print(even_number)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [21]:
# Exercise 10
matrix_of_6 = np.random.randint(10,51,size=(6,6))
print(matrix_of_6)


[[44 14 36 45 23 14]
 [40 16 15 20 41 44]
 [18 30 36 42 24 21]
 [48 17 29 50 30 34]
 [10 39 10 40 30 29]
 [16 18 42 14 20 27]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [22]:
# Exercise 11
matrix = np.array([
    [ 0,  1,  2,  3,  4],
    [ 5,  6,  7,  8, 9],
    [10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19],
    [20, 21, 22, 23, 24]
])
sub_matrix=matrix[1:4,1:4]
sub_matrix

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [24]:
# Exercise 12
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.add(a,b))

[[ 6  8]
 [10 12]]



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [25]:
# Exercise 13
d= np.array([1,2,3,4,4,6,7,8])
d_mean=np.mean(d)
print('mean_is=',d_mean)
print('*********************')
d_median=np.median(d)
print('median_is=',d_median)
print('*********************')
d_standard=np.std(d)
print('standard deviation_is=',d_standard)
print('**********************')

mean_is= 4.375
median_is= 4.0
standard deviation_is= 2.2878756522153907



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [27]:
# Exercise 14
b=np.array([1,0,4,6,5,7,8,10])
b_max=np.max(b)
b_min=np.min(b)
print(b_min)
print(b_max)


0
10



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [28]:
# Exercise 15
a=np.random.randint(1,50,size=20)
max_a=np.argmax(a)
print(a)
print(len(a))
print(a[max_a])
print(max_a)


[24 44  3 22 11 24 28  2 24 39 46 47 36  7 38  1 12 18 42 21]
20
47
11



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [29]:
# Exercise 16
x=np.array([1,2,3,5,6,7,8,10])
x_reverse=x[::-1]
print(x_reverse)

[10  8  7  6  5  3  2  1]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [30]:
# Exercise 17
a=np.array([[0,2,4],[3,7,8],[0,3,4]])
b=np.array([[1,4,6],[1,4,6],[2,3,1]])
print(np.dot(a,b))

[[10 20 16]
 [26 64 68]
 [11 24 22]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [31]:
# Exercise 18
a=np.array([15,25,35,45])
a_diagonal=np.diag(a)
print(a_diagonal)

[[15  0  0  0]
 [ 0 25  0  0]
 [ 0  0 35  0]
 [ 0  0  0 45]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [32]:
# Exercise 19
a=np.array([[2,1],[4,3]])
b=np.array([[4,6],[5,6]])
result=np.dot(a,b)
print('a matrix:\n',a)
print('b matrix:\n',b)
print('result matrix:\n',result)

a matrix:
 [[2 1]
 [4 3]]
b matrix:
 [[4 6]
 [5 6]]
result matrix:
 [[13 18]
 [31 42]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [33]:
# Exercise 20
a=np.array([[0,1,2],[3,4,5]])
b=a.flatten()
print('2D IS:\n',a)
print('1D IS:\n',b)

2D IS:
 [[0 1 2]
 [3 4 5]]
1D IS:
 [0 1 2 3 4 5]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [34]:
# Exercise 21
x=np.array([[0,1],[2,3]])
y=np.array([[4,5],[6,7]])

stack_array=np.vstack((x,y))
print('x :\n',x)
print('y :\n',y)
print('Vertical stack:\n',stack_array)

x :
 [[0 1]
 [2 3]]
y :
 [[4 5]
 [6 7]]
Vertical stack:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [35]:
# Exercise 22
# Exercise 21
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

stack_array=np.hstack((a,b))
print('x :\n',a)
print('y :\n',b)
print('Horzontal stack:\n',stack_array)

x :
 [[1 2]
 [3 4]]
y :
 [[5 6]
 [7 8]]
Horzontal stack:
 [[1 2 5 6]
 [3 4 7 8]]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [40]:
# Exercise 23
x=np.array([0,3,4,6,7,8])
x_split=np.split(x,3)
print(x_split)

[array([0, 3]), array([4, 6]), array([7, 8])]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [42]:
# Exercise 24
a=np.random.rand(4,4)
a_round=np.round(a,2)
print(a)
print("*********************\n")
print(a_round)

[[0.84938802 0.15551099 0.03330324 0.22052785]
 [0.56220766 0.54645801 0.02217834 0.03052765]
 [0.71096015 0.28387294 0.08088621 0.59936084]
 [0.38164181 0.42044926 0.71806381 0.53609931]]
*********************

[[0.85 0.16 0.03 0.22]
 [0.56 0.55 0.02 0.03]
 [0.71 0.28 0.08 0.6 ]
 [0.38 0.42 0.72 0.54]]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [43]:
# Exercise 25
y = np.array([1,0,2,3,3,4,5,6,7,8,3,4])
y_unique = np.unique(y)
print(y_unique)

[0 1 2 3 4 5 6 7 8]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [44]:
# Exercise 26
x=np.array([1,2,3,4,5,6,7,8,9,10])
x[x <5]=5
print(x)

[ 5  5  5  5  5  6  7  8  9 10]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [45]:
# Exercise 27
nbr = np.array([0,1,2,3,4])
cumulative_sum_of_nbr=np.cumsum(nbr)
print('number is:\n',nbr)
print('Cumulative sum:\n',cumulative_sum_of_nbr)

number is:
 [0 1 2 3 4]
Cumulative sum:
 [ 0  1  3  6 10]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [47]:
# Exercise 28
c = np.array([5,10,2,1,3,0,4])
non_xero_of_c=np.count_nonzero(c)
print(c)
print(non_xero_of_c)

[ 5 10  2  1  3  0  4]
6



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [48]:
# Exercise 29
a = np.random.randint(1,20,size=10)
Ascending_of_a = np.sort(a)
print(a)
print(Ascending_of_a)

[ 4 16 11  1 17  6  2  4 19 15]
[ 1  2  4  4  6 11 15 16 17 19]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [49]:
# Exercise 30
x = np.array([[2,3,4],[5,6,7],[8,9,10]])
row_wise = np.sum(x,axis=1)
column_wise = np.sum(x,axis=0)
print('X is:\n',x)
print('Row wise:\n',row_wise)
print('Column wise:\n',column_wise)

X is:
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Row wise:
 [ 9 18 27]
Column wise:
 [15 18 21]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [50]:
# Exercise 31
a = np.random.randint(10,100,size=(3,4))
a_min = a.min()
a_max = a.max()
normalize_a=(a - a_min)/(a_max - a_min)
print("a is:\n",a)
print("*****************************")
print("normarlize for a is:\n",normalize_a)

a is:
 [[16 55 99 43]
 [11 67 85 50]
 [66 67 48 86]]
*****************************
normarlize for a is:
 [[0.05681818 0.5        1.         0.36363636]
 [0.         0.63636364 0.84090909 0.44318182]
 [0.625      0.63636364 0.42045455 0.85227273]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [51]:
# Exercise 32
x = np.array([0, 1, 2])
y= np.array([3, 4, 5])

dot_product = np.dot(x, y)

print("Dot Product is:", dot_product)

Dot Product is: 14



---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [52]:
# Exercise 33
import numpy as np


n = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


trace_value_ = np.trace(n)

print("Trace of the matrix:", trace_value_)


Trace of the matrix: 15



---

### Exercise 34:
Create a 2D array and swap two rows.


In [55]:
# Exercise 34
array_of_2d = np.array([[15, 25, 35],
                     [45, 55, 65],
                     [75, 85, 95]])

print("Original array:")
print(array_of_2d)


array_of_2d[[0, 2]] = array_of_2d[[2, 0]]

print("\nArray after swapping row 0 and row 3:")
print(array_of_2d)

Original array:
[[15 25 35]
 [45 55 65]
 [75 85 95]]

Array after swapping row 0 and row 3:
[[75 85 95]
 [45 55 65]
 [15 25 35]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [56]:
# Exercise 35
array_of_1d = np.array([0, 1, 2, 3, 4])

column_vector = array_of_1d.reshape(-1, 1)

print("Column vector is:")
print(column_vector)

Column vector is:
[[0]
 [1]
 [2]
 [3]
 [4]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [57]:
# Exercise 36
matrix = np.array([[1, 4, 3],
                   [2, -2, -1],
                   [1, 3, 4]])

determinant = np.linalg.det(matrix)

print("Determinant is:", determinant)

Determinant is: -16.999999999999993



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [58]:
# Exercise 37
matrix = np.array([[3, 2],
                   [1, 4]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues are:")
print(eigenvalues)

print("\nEigenvectors are:")
print(eigenvectors)

Eigenvalues are:
[2. 5.]

Eigenvectors are:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [61]:
# Exercise 38
x = np.array([[2, 4],
              [4, 5]])

y = np.array([9, 12])

result = np.linalg.solve(x, y)

print("result [n, m]:", result)

result [n, m]: [0.5 2. ]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [62]:
# Exercise 39
original_array = np.array([10, 20, 30, 40, 50])

mean = 0       
std_dev = 2   

noise = np.random.normal(mean, std_dev, original_array.shape)

noisy_array = original_array + noise

print("Original array:", original_array)
print("Noise:", noise)
print("Noisy array:", noisy_array)

Original array: [10 20 30 40 50]
Noise: [-2.29718805  1.32376354  0.1418216  -0.61023318 -0.28041999]
Noisy array: [ 7.70281195 21.32376354 30.1418216  39.38976682 49.71958001]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [63]:
# Exercise 40
matrix_ = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

diagonal_elements = np.diag(matrix_)

print("Original matrix is :")
print(matrix_)

print("\nDiagonal elements are:")
print(diagonal_elements)


Original matrix is :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Diagonal elements are:
[ 1  6 11 16]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [64]:
# Exercise 41
from_=10
to_=50
size=100
x=np.random.randint(from_,to_,size)
print(x)
print(len(x))

[44 24 31 40 27 32 26 42 44 36 37 30 44 42 34 31 27 31 21 10 28 36 27 23
 49 22 21 33 29 40 18 19 31 31 14 32 38 30 21 28 19 45 19 23 17 32 39 36
 49 21 10 39 44 14 18 10 42 41 49 41 30 36 25 34 37 19 25 37 23 49 14 22
 36 34 20 16 11 15 24 24 40 47 19 46 33 22 46 28 35 16 48 20 34 15 48 37
 18 12 34 48]
100



---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [65]:
# Exercise 42
x = np.array([[2,-3,-2],[-1,6,-4]])
x[x <0] = 0
print(x)

[[2 0 0]
 [0 6 0]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [67]:
# Exercise 43
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

inner_product=np.inner(x,y)
outer_product=np.outer(x,y)

print("Inner product is:", inner_product)
print("\nOuter product are:\n", outer_product)

Inner product is: 32

Outer product are:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [71]:
# Exercise 44
from scipy.spatial import distance_matrix
p = np.array([[0, 0],
                   [1, 1],
                   [2, 0]])
dist_matrix = distance_matrix(p, p)

print("Pairwise distance matrix are:")
print(dist_matrix)

Pairwise distance matrix are:
[[0.         1.41421356 2.        ]
 [1.41421356 0.         1.41421356]
 [2.         1.41421356 0.        ]]



---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [76]:
# Exercise 45
person = np.dtype([('name', 'U20'), 
                         ('age', 'i4'),    
                         ('height', 'f4')]) 

people = np.array([('Ange', 24, 6.5),
                   ('Lex', 31, 5.0),
                   ('Aime', 24, 6.8)], dtype=person)

print(people)

[('Ange', 24, 6.5) ('Lex', 31, 5. ) ('Aime', 24, 6.8)]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [77]:
# Exercise 46
matrix = np.random.randint(1, 11, size=(5, 5))

print("Matrix is:")
print(matrix)

unique_values, counts = np.unique(matrix, return_counts=True)

for val, count in zip(unique_values, counts):
    print(f"Value {val} occurs {count} times")

Matrix is:
[[ 6  5 10  4  3]
 [ 9 10  3  2  1]
 [ 8  9  6  6  6]
 [ 1  7  6  2  4]
 [ 5  4  2  9  4]]
Value 1 occurs 2 times
Value 2 occurs 3 times
Value 3 occurs 2 times
Value 4 occurs 4 times
Value 5 occurs 2 times
Value 6 occurs 5 times
Value 7 occurs 1 times
Value 8 occurs 1 times
Value 9 occurs 3 times
Value 10 occurs 2 times



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [80]:
# Exercise 47
array_ = np.random.rand(3, 3)
row_means = array_.mean(axis=1, keepdims=True)
solution = array_ - row_means
print('Array is:\n',array_)
print("*************************")
print("Mean is\n",row_means)
print("**************************")
print("solution is:\n",solution)

Array is:
 [[0.01549463 0.96097016 0.08690142]
 [0.37700808 0.28991636 0.96035493]
 [0.43451006 0.05851731 0.6548254 ]]
*************************
Mean is
 [[0.3544554 ]
 [0.54242646]
 [0.38261759]]
**************************
solution is:
 [[-0.33896077  0.60651475 -0.26755398]
 [-0.16541838 -0.25251009  0.41792848]
 [ 0.05189247 -0.32410028  0.27220781]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [81]:
# Exercise 48
array_ = np.random.randint(0, 200, size=10)
any_greater_than_50 = np.any(array_ > 50)

print(array_)
print("Any values greater than 50:", any_greater_than_50)

[ 66  27 197 115  18   1 183  89  63  18]
Any values greater than 50: True



---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [82]:
# Exercise 49
def moving_average(array_, window_size):
    return np.convolve(array_, np.ones(window_size)/window_size, mode='valid')

array_ = np.array([0, 1, 3, 4, 5, 6, 7, 8, 9])
window_size = 3
m = moving_average(array_, window_size)

print(m)

[1.33333333 2.66666667 4.         5.         6.         7.
 8.        ]



---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [83]:
# Exercise 50
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

correlation = np.corrcoef(a, b)[0, 1]


print("Pearson correlation coefficient is:", correlation)

Pearson correlation coefficient is: -0.9999999999999999



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [84]:
# Exercise 51
rad = np.array([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
degr = np.degrees(rad)

print(degr)

[  0.  90. 180. 270. 360.]



---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [85]:
# Exercise 52
arr = np.random.rand(15)
variance = np.var(arr)
std_dev = np.std(arr)

print("Array is:", arr)
print("Variance is:", variance)
print("Standard Deviation is:", std_dev)

Array is: [0.96859415 0.64464826 0.48643883 0.77572987 0.61839849 0.61840521
 0.2786847  0.33392322 0.04364096 0.03858797 0.47812066 0.22069565
 0.16871404 0.51124683 0.92632226]
Variance is: 0.08017118588816716
Standard Deviation is: 0.28314516751688906



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [86]:
# Exercise 53
array_ = np.random.rand(5, 6)
max_indices_axis0 = np.argmax(array_, axis=0)
max_indices_axis1 = np.argmax(array_, axis=1)

print("Array is:\n", array_)
print("Indices of max values along axis 0:", max_indices_axis0)
print("Indices of max values along axis 1:", max_indices_axis1)

Array is:
 [[0.65601972 0.65441511 0.87001857 0.69122968 0.99942541 0.07951424]
 [0.68325981 0.33931326 0.86153882 0.67588866 0.84584756 0.30703347]
 [0.68611507 0.1997683  0.43538075 0.81101969 0.31939736 0.56890843]
 [0.27785488 0.34224983 0.72439738 0.79436665 0.27427822 0.43677284]
 [0.39745808 0.26302382 0.89986324 0.68826907 0.38643758 0.79726688]]
Indices of max values along axis 0: [2 0 4 2 0 4]
Indices of max values along axis 1: [4 2 3 3 2]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [87]:
# Exercise 54
matrix = np.array([[5, 7],
                   [3, 6]])

inverse = np.linalg.inv(matrix)

print("Inverse matrix is:")
print(inverse)

Inverse matrix is:
[[ 0.66666667 -0.77777778]
 [-0.33333333  0.55555556]]



---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [89]:
# Exercise 55
arr = np.random.rand(10)
standardized = (arr - np.mean(arr)) / np.std(arr)

print("Original array is:", arr)
print("Standardized array is:", standardized)

Original array is: [0.9449394  0.82399021 0.76417912 0.99567668 0.2717485  0.28273254
 0.48190058 0.7858364  0.24768673 0.36280964]
Standardized array is: [ 1.24109761  0.81072402  0.59789819  1.42163611 -1.15431798 -1.11523347
 -0.40653371  0.67496133 -1.23993699 -0.83029509]



---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [90]:
# Exercise 56
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

addition = x + y
subtraction = x - y

print("Addition:", addition)
print("Subtraction:", subtraction)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [118]:
# Exercise 57
arr = np.random.rand(10)
max_index = np.argmax(arr)

print("Array:", arr)
print("Index of maximum element:", max_index)

Array: [0.49119605 0.01193675 0.71481856 0.71081121 0.21428402 0.54149661
 0.9760695  0.32759892 0.48361486 0.61954409]
Index of maximum element: 6



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [92]:
# Exercise 58
array_ = np.array([[0, 2, 4],
                [9, 5, 6],
                [7, 8, 6]])

rotated = np.rot90(array_)

print(rotated)

[[4 6 6]
 [2 5 8]
 [0 9 7]]



---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [93]:
# Exercise 59
matrix = np.array([[3, 2],
                   [5, 4]])

frobenius_norm = np.linalg.norm(matrix, 'fro')

print("Frobenius norm:", frobenius_norm)

Frobenius norm: 7.3484692283495345



---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [94]:
# Exercise 60
array_ = np.arange(27).reshape((3, 3, 3))

subarray = array_[1:, :2, 1:]

print("Original array is:\n", arr)
print("\nSliced subarray is:\n", subarray)

Original array is:
 [0.9449394  0.82399021 0.76417912 0.99567668 0.2717485  0.28273254
 0.48190058 0.7858364  0.24768673 0.36280964]

Sliced subarray is:
 [[[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]



---